language: ruby

# Apparently sudo is required to test on Rubinius and JRuby-head
sudo: required

# See https://docs.travis-ci.com/user/languages/ruby/#Rubinius
dist: trusty

rvm:
  # MRI
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - 1.9.3
  # JRuby
  - jruby-head
  - jruby-9.2
  # Truffleruby
  - truffleruby-head
  - truffleruby-20.3.0

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby-head
    # NOTE (2020-12-18): Failing access to Rubygems with following error:
    #   Unable to download data from https://rubygems.org/ - hostname was not
    #   match with the server certificate (https://rubygems.org/specs.4.8.gz)
    # TODO (2020-12-18): Either find a fix or remove testing of 1.8 versions
    - rvm: 1.8.7
    - rvm: ree

  fast_finish: true
